import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Socials } from "@/components/ui/navbars/socials";
import { Navbar } from "@/components/ui/navbars/nav-bar";
import { ContactAndServices } from "@/components/ui/navbars/contact-and-services";
import { Toaster } from "sonner";
import { appName } from "@/constants/constant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: appName,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <div className="w-full h-14 bg-black flex items-center justify-center">
            <h2 className="text-white font-bold text-2xl">NOTIFICATION BAR</h2>
          </div>
          <Socials />
          <Navbar />
          <div className="hidden  lg:block xl:block">
            <ContactAndServices />
          </div>
          {children}
        </main>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
